// source: file/userfile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.services.UserFile', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.UserFile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.UserFile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.UserFile.displayName = 'proto.services.UserFile';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.UserFile.prototype.toObject = function(opt_includeInstance) {
  return proto.services.UserFile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.UserFile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.UserFile.toObject = function(includeInstance, msg) {
  var f, obj = {
    identity: jspb.Message.getFieldWithDefault(msg, 1, ""),
    hash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userIdentity: jspb.Message.getFieldWithDefault(msg, 3, 0),
    path: jspb.Message.getFieldWithDefault(msg, 4, ""),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ext: jspb.Message.getFieldWithDefault(msg, 6, ""),
    size: jspb.Message.getFieldWithDefault(msg, 7, 0),
    deleted: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    parent: jspb.Message.getFieldWithDefault(msg, 9, ""),
    type: jspb.Message.getFieldWithDefault(msg, 10, 0),
    directory: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    atime: jspb.Message.getFieldWithDefault(msg, 12, 0),
    ctime: jspb.Message.getFieldWithDefault(msg, 13, 0),
    mtime: jspb.Message.getFieldWithDefault(msg, 14, 0),
    version: jspb.Message.getFieldWithDefault(msg, 15, 0),
    locking: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    op: jspb.Message.getFieldWithDefault(msg, 17, 0),
    preview: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
    previewType: jspb.Message.getFieldWithDefault(msg, 19, 0),
    flag: jspb.Message.getFieldWithDefault(msg, 20, 0),
    uniqueIdentity: jspb.Message.getFieldWithDefault(msg, 21, ""),
    share: jspb.Message.getBooleanFieldWithDefault(msg, 22, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.UserFile}
 */
proto.services.UserFile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.UserFile;
  return proto.services.UserFile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.UserFile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.UserFile}
 */
proto.services.UserFile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentity(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserIdentity(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setExt(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeleted(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDirectory(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAtime(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCtime(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMtime(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVersion(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLocking(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOp(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPreview(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreviewType(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFlag(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setUniqueIdentity(value);
      break;
    case 22:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShare(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.UserFile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.UserFile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.UserFile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.UserFile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentity();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserIdentity();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getExt();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getDeleted();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getType();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getDirectory();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getAtime();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getCtime();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getMtime();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getLocking();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getOp();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = message.getPreview();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getPreviewType();
  if (f !== 0) {
    writer.writeInt32(
      19,
      f
    );
  }
  f = message.getFlag();
  if (f !== 0) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = message.getUniqueIdentity();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getShare();
  if (f) {
    writer.writeBool(
      22,
      f
    );
  }
};


/**
 * optional string identity = 1;
 * @return {string}
 */
proto.services.UserFile.prototype.getIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string hash = 2;
 * @return {string}
 */
proto.services.UserFile.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 user_identity = 3;
 * @return {number}
 */
proto.services.UserFile.prototype.getUserIdentity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setUserIdentity = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string path = 4;
 * @return {string}
 */
proto.services.UserFile.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.services.UserFile.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string ext = 6;
 * @return {string}
 */
proto.services.UserFile.prototype.getExt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setExt = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 size = 7;
 * @return {number}
 */
proto.services.UserFile.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional bool deleted = 8;
 * @return {boolean}
 */
proto.services.UserFile.prototype.getDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setDeleted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional string parent = 9;
 * @return {string}
 */
proto.services.UserFile.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 type = 10;
 * @return {number}
 */
proto.services.UserFile.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional bool directory = 11;
 * @return {boolean}
 */
proto.services.UserFile.prototype.getDirectory = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setDirectory = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional int64 atime = 12;
 * @return {number}
 */
proto.services.UserFile.prototype.getAtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setAtime = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 ctime = 13;
 * @return {number}
 */
proto.services.UserFile.prototype.getCtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setCtime = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int64 mtime = 14;
 * @return {number}
 */
proto.services.UserFile.prototype.getMtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setMtime = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 version = 15;
 * @return {number}
 */
proto.services.UserFile.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional bool locking = 16;
 * @return {boolean}
 */
proto.services.UserFile.prototype.getLocking = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setLocking = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional int32 op = 17;
 * @return {number}
 */
proto.services.UserFile.prototype.getOp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setOp = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional bool preview = 18;
 * @return {boolean}
 */
proto.services.UserFile.prototype.getPreview = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setPreview = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional int32 preview_type = 19;
 * @return {number}
 */
proto.services.UserFile.prototype.getPreviewType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setPreviewType = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional int32 flag = 20;
 * @return {number}
 */
proto.services.UserFile.prototype.getFlag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setFlag = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional string unique_identity = 21;
 * @return {string}
 */
proto.services.UserFile.prototype.getUniqueIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setUniqueIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional bool share = 22;
 * @return {boolean}
 */
proto.services.UserFile.prototype.getShare = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 22, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.UserFile} returns this
 */
proto.services.UserFile.prototype.setShare = function(value) {
  return jspb.Message.setProto3BooleanField(this, 22, value);
};


goog.object.extend(exports, proto.services);
